name: node-red-nats-cli
base: core20
version: '1.0'
summary: ThingsBoard IoT Gateway
description: |
  This snap installs and runs ThingsBoard IoT Gateway, which helps you to integrate devices connected to legacy and third-party systems with ThingsBoard.

confinement: strict
grade: stable

parts:
  thingsboard-gateway:
    plugin: python
    source: https://github.com/thingsboard/thingsboard-gateway.git
    build-packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel  # Mogelijk nodig voor bepaalde Python dependencies
    override-pull: |
      snapcraftctl pull
      # Voeg hier eventuele pull acties toe indien nodig
    override-build: |
      python3 -m venv $SNAPCRAFT_PART_INSTALL
      . $SNAPCRAFT_PART_INSTALL/bin/activate
      pip install -r requirements.txt
      python setup.py install

apps:
  thingsboard-gateway:
    command: bin/python3 -m thingsboard_gateway
    plugs: [network, network-bind, home]
